# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9213a29d09f054db64312f54fbb5c44ebc0de6a6f0c867c56d382d92e4257b9a424af48f93322ef26ac0281a3e2b91731e900cbc2a26f4562e5348fa500a88df

test:
  secret_key_base: af5b5be7a1124384d9892a960cec89accbaeefd8e62f03e28843098744f69ac28a2a59254eae0c8f03c56e833609af75ec853f9f323552082e7f961adad76c00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
